name: Run Basic Testes

on:
   pull_request:
        branches: [master]

jobs:
  cypress-run:
      runs-on: ubuntu-latest
      
      steps:

        - name: Checkout/Clone do projeto
          uses: actions/checkout@v4

        - name: Run tests
          uses: cypress-io/github-action@v6
          with:
            record: true
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
         
        - name: Upload Report
          uses: actions/upload-artifact@v4
          with:
            name: Relatórios
            path: cypress/repors/html

            
